# Autogenerated Python bindings for MyStruct
# Do not edit this file directly

from ctypes import CDLL, Structure, POINTER, c_int, c_char_p

libzigpy = CDLL("./zig-out/lib/libzigpy.dylib")

class MyStruct(Structure):
    _fields_ = [("a", c_int), ("b", c_int), ]

libzigpy.codegenstruct___init__.restype = POINTER(MyStruct)
libzigpy.codegenstruct___del__.argtypes = [POINTER(MyStruct)]

class MyStruct():
  def __init__(self):
    self.ptr = libzigpy.codegenstruct___init__()

  def __del__(self):
    libzigpy.codegenstruct___del__(self.ptr)


  @property
  def a(self):
      return self.ptr.contents.a

  @a.setter
  def a(self, value):
      self.ptr.contents.a = value


  @property
  def b(self):
      return self.ptr.contents.b

  @b.setter
  def b(self, value):
      self.ptr.contents.b = value


  def print(self): 
      return libzigpy.codegenstruct_print(self.ptr)


  def print_pystring(self, arg1: str): 
      c_arg1 = c_char_p(arg1.encode('utf-8'))
      return libzigpy.codegenstruct_print_pystring(self.ptr, c_arg1)


