# Autogenerated Python bindings for MyStruct
# Do not edit this file directly

from ctypes import CDLL, Structure, POINTER, c_int, c_void_p, c_char_p

libzigpy = CDLL("./zig-out/lib/libzigpy.dylib")

class MyStruct(Structure):
    _fields_ = []

# generated special zig types
class _PyString(Structure):
   _fields_ = [("value", c_char_p)]

libzigpy.codegenstruct___init__.restype = POINTER(MyStruct)
libzigpy.codegenstruct___del__.argtypes = [POINTER(MyStruct)]

# define c interfaces
libzigpy.codegenstruct_get_static_str.argtypes = [POINTER(MyStruct)]
libzigpy.codegenstruct_get_static_str.restype = _PyString

class MyStruct():
  def __init__(self):
    self.ptr = libzigpy.codegenstruct___init__()

  def __del__(self):
    libzigpy.codegenstruct___del__(self.ptr)

  def get_static_str(self): 
      c_res_wrapped = libzigpy.codegenstruct_get_static_str(self.ptr)
      c_res = c_res_wrapped.value # always .value
      res = c_res.decode('utf-8') # conversion
      return res


