# Autogenerated Python bindings for MyStruct
# Do not edit this file directly

from ctypes import CDLL, Structure, POINTER, c_int, c_void_p

libzigpy = CDLL("./zig-out/lib/libzigpy.dylib")

# Public class
class MyStruct(Structure):
    _fields_ = [("a", c_int), ("b", c_int), ]

# Shared Library Function interfaces
libzigpy.codegenstruct___init__.restype = POINTER(MyStruct)
libzigpy.codegenstruct___del__.argtypes = [POINTER(MyStruct)]
libzigpy.codegenstruct_sum.argtypes = []
libzigpy.codegenstruct_sum.restype = c_int
libzigpy.codegenstruct_update.argtypes = [c_int, c_int, ]
libzigpy.codegenstruct_update.restype = c_void_p
class MyStruct():
  def __init__(self):
    self.ptr = libzigpy.codegenstruct___init__()
  def __del__(self):
    libzigpy.codegenstruct___del__(self.ptr)

  @property
  def a(self):
      return self.ptr.contents.a
  @a.setter
  def a(self, value: int):
      self.ptr.contents.a = value

  @property
  def b(self):
      return self.ptr.contents.b
  @b.setter
  def b(self, value: int):
      self.ptr.contents.b = value


  def sum(self):
      # todo
      return libzigpy.codegenstruct_sum(self.ptr)

  def update(self, arg1: int, arg2: int):
      # todo
      return libzigpy.codegenstruct_update(self.ptr, arg1, arg2)

