# Autogenerated Python bindings for MyStruct
# Do not edit this file directly

from ctypes import CDLL, Structure, POINTER, c_int, c_void_p, c_char_p

libzigpy = CDLL("./zig-out/lib/libzigpy.dylib")

class MyStruct(Structure):
    _fields_ = [("a", c_int), ("b", c_int), ]

libzigpy.codegenstruct___init__.restype = POINTER(MyStruct)
libzigpy.codegenstruct___del__.argtypes = [POINTER(MyStruct)]

# define c interfaces
libzigpy.codegenstruct_print.argtypes = [POINTER(MyStruct)]
libzigpy.codegenstruct_print.restype = c_void_p
libzigpy.codegenstruct_print_pystring.argtypes = [POINTER(MyStruct), c_char_p]
libzigpy.codegenstruct_print_pystring.restype = c_void_p
libzigpy.codegenstruct_sum.argtypes = [POINTER(MyStruct)]
libzigpy.codegenstruct_sum.restype = c_int
libzigpy.codegenstruct_get_static_str.argtypes = [POINTER(MyStruct)]
libzigpy.codegenstruct_get_static_str.restype = c_char_p

class MyStruct():
  def __init__(self):
    self.ptr = libzigpy.codegenstruct___init__()

  def __del__(self):
    libzigpy.codegenstruct___del__(self.ptr)


  @property
  def a(self):
      return self.ptr.contents.a

  @a.setter
  def a(self, value):
      self.ptr.contents.a = value


  @property
  def b(self):
      return self.ptr.contents.b

  @b.setter
  def b(self, value):
      self.ptr.contents.b = value


  def print(self): 
      c_res = libzigpy.codegenstruct_print(self.ptr)
      res = c_res
      return res


  def print_pystring(self, arg1: str): 
      c_arg1 = arg1.encode('utf-8')
      c_res = libzigpy.codegenstruct_print_pystring(self.ptr, c_arg1)
      res = c_res
      return res


  def sum(self): 
      c_res = libzigpy.codegenstruct_sum(self.ptr)
      res = c_res
      return res


  def get_static_str(self): 
      c_res = libzigpy.codegenstruct_get_static_str(self.ptr)
      res = c_res.decode('utf-8')
      return res


